{
 "title": "CRUDEAPP DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency (GET)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{method = 'GET'}[5m])) by (le))",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{method = 'GET'}[5m])) by (le))",
     "legendFormat": "0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method = 'GET'}[5m])) by (le))",
     "legendFormat": "0.99 quantile"
    },
    {
     "expr": "max(http_server_requests_seconds_bucket{method='GET'})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Latency (POST)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{method = 'POST'}[5m])) by (le))",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{method = 'POST'}[5m])) by (le))",
     "legendFormat": "0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method = 'POST'}[5m])) by (le))",
     "legendFormat": "0.99 quantile"
    },
    {
     "expr": "max(http_server_requests_seconds_bucket{method='POST'})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status='500'}[2m]))",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method='GET'}[2m]))",
     "legendFormat": "RPS GET"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method='POST'}[2m]))",
     "legendFormat": "RSP POST"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method='PUT'}[2m]))",
     "legendFormat": "RSP PUT"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method='DELETE'}[2m]))",
     "legendFormat": "RSP DELETE"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_requests_total[1m]) ",
     "legendFormat": "nginx-controller RPS"
    }
   ]
  }
 ]
}